#! /bin/sh
### BEGIN INIT INFO
# Provides: node_exporter
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: node_exporter
# Description: This file starts and stops node_exporter
# 
### END INIT INFO

NODE_EXPORTER=/usr/local/bin/node_exporter

case "$1" in
 start)
   su node_exporter -c $NODE_EXPORTE
   ;;
*)
   echo "Usage: start only" >&2
   exit 3
   ;;
esac
